services:
  app:
    image: toras9000/excalidraw-mp:v0.17.3
    build:
      context: ./build/app
      args:
        - EXCALIDRAW_REV=v0.17.3
      x-bake:
        tags:
          - toras9000/excalidraw-mp:v0.17.3
          - toras9000/excalidraw-mp:latest
          - ghcr.io/toras9000/docker-excalidraw:v0.17.3
          - ghcr.io/toras9000/docker-excalidraw:latest
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        pull: true
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      - TZ=Asia/Tokyo
      - VITE_APP_WS_SERVER_URL=http://localhost:8002/

  collabo:
    image: toras9000/excalidraw-room-mp:v2023.12.15
    build:
      context: ./build/room
      args:
        - EXCALIDRAW_ROOM_REV=03ff435860b508d7cd9e005cfc90f7977ae2a593
      x-bake:
        tags:
          - toras9000/excalidraw-room-mp:v2023.12.15
          - toras9000/excalidraw-room-mp:latest
          - ghcr.io/toras9000/docker-excalidraw-room:v2023.12.15
          - ghcr.io/toras9000/docker-excalidraw-room:latest
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        pull: true
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      - TZ=Asia/Tokyo
