version: '3.5'

services:
  app:
    image: toras9000/excalidraw-mp:v0.15.0
    build:
      context: ./build/app
      args:
        - EXCALIDRAW_REV=v0.15.0
      x-bake:
        tags:
          - toras9000/excalidraw-mp:v0.15.0
          - toras9000/excalidraw-mp:latest
          - ghcr.io/toras9000/docker-excalidraw:v0.15.0
          - ghcr.io/toras9000/docker-excalidraw:latest
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        pull: true
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      - TZ=Asia/Tokyo
      - REACT_APP_WS_SERVER_URL=http://localhost:8002/

  collabo:
    image: toras9000/excalidraw-room-mp:v2023.05.16
    build:
      context: ./build/room
      args:
        - EXCALIDRAW_ROOM_REV=b6547a66d79898e51174096bcbb2c37b829917bd
      x-bake:
        tags:
          - toras9000/excalidraw-room-mp:v2023.05.16
          - toras9000/excalidraw-room-mp:latest
          - ghcr.io/toras9000/docker-excalidraw-room:v2023.05.16
          - ghcr.io/toras9000/docker-excalidraw-room:latest
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        pull: true
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      - TZ=Asia/Tokyo
