version: '3.5'

services:
  app:
    image: toras9000/excalidraw-mp:v0.16.1
    build:
      context: ./build/app
      args:
        - EXCALIDRAW_REV=v0.16.1
      x-bake:
        tags:
          - toras9000/excalidraw-mp:v0.16.1
          - toras9000/excalidraw-mp:latest
          - ghcr.io/toras9000/docker-excalidraw:v0.16.1
          - ghcr.io/toras9000/docker-excalidraw:latest
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        pull: true
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      - TZ=Asia/Tokyo
      - VITE_APP_WS_SERVER_URL=http://localhost:8002/

  collabo:
    image: toras9000/excalidraw-room-mp:v2023.05.27
    build:
      context: ./build/room
      args:
        - EXCALIDRAW_ROOM_REV=49bf529ea1f9448f1a6f77ae051092585162e132
      x-bake:
        tags:
          - toras9000/excalidraw-room-mp:v2023.05.27
          - toras9000/excalidraw-room-mp:latest
          - ghcr.io/toras9000/docker-excalidraw-room:v2023.05.27
          - ghcr.io/toras9000/docker-excalidraw-room:latest
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        pull: true
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      - TZ=Asia/Tokyo
